#!/usr/bin/env bash
set -euo pipefail

source /opt/miniconda3/etc/profile.d/conda.sh
conda activate tskit-dev-1
CONNECTION_FILE="$1"
# gdb <<< "python import sys; sys.stdout = open('test-stdout.txt', 'a'); sys.stderr = open('test-stderr.txt', 'a'); from ipykernel import kernelapp; kernelapp.connection_file='"$CONNECTION_FILE"'; kernelapp.launch_new_instance()"

gdb <<< "python import sys; sys.stdout = open('/dev/null', 'a'); sys.stderr = open('/dev/null', 'a'); import IPython; IPython.embed_kernel(connection_file='"$CONNECTION_FILE"')"
