#!/bin/sh

set -e

[ $(command -v awk) ] || (echo 'awk is not installed'; exit 1)
[ $(command -v conda) ] || (echo 'conda is not installed'; exit 1)
[ $(command -v basename) ] || (echo 'basename is not installed'; exit 1)

conda_env_list="$(conda env list | awk '$1!="#" && $1!="base" && $1 {print $1}')"

for env_name in $conda_env_list; do
    echo "Backing up $env_name"
    conda env export --name "$env_name" | grep -Ev -e '^prefix: ' -e '^name: ' > "envs/${env_name}.yml"
    conda env export --from-history --name "$env_name" | grep -Ev -e '^prefix: ' -e '^name: ' > "envs-from-history/${env_name}.yml"
done

for env_dir in envs envs-from-history; do
    for env_file in $env_dir/*; do
	env_name="$(basename -s .yml "$env_file")"
	if ! echo "$conda_env_list" | grep -q "$env_name"; then
	    echo "$env_name does not exist, deleting $env_file"
	    rm "$env_file"
	fi
    done
done
