#!/bin/sh

set -e

[ $(command -v jq) ] || (echo 'jq is not installed'; exit 1)
[ $(command -v conda) ] || (echo 'conda is not installed'; exit 1)
[ $(command -v basename) ] || (echo 'basename is not installed'; exit 1)

for conda_env_dir in $(conda env list --json | jq -r '.envs[]'); do
    conda_env_name="$(basename "$conda_env_dir")"
    if [ $conda_env_name = "miniconda3" ]; then
        continue
    fi
    echo "Backing up $conda_env_name"
    conda env export --name "$conda_env_name" | grep -Ev -e '^prefix: ' -e '^name: ' > "envs/${conda_env_name}.yml"
    conda env export --from-history --name "$conda_env_name" | grep -Ev -e '^prefix: ' -e '^name: ' > "envs-from-history/${conda_env_name}.yml"
done